// @ts-nocheck
import React from 'react';
import { Warehouse, Phone, Mail, Eye, Edit, Trash2 } from 'lucide-react';
import { Avatar, Box, Card, Chip, IconButton, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TableSortLabel, Tooltip, Typography } from '@mui/material';

export default function WarehouseTable({ items, sortBy, sortOrder, onSort, isAdmin, onView, onEdit, onDelete }) {
  const date = (value) => new Date(value).toLocaleDateString('en-NZ', { year: 'numeric', month: 'short', day: 'numeric' });
  const actions = (warehouse) => <Stack direction="row" justifyContent="flex-end"><Tooltip title="View Details"><IconButton onClick={() => onView(warehouse)}><Eye size={18} /></IconButton></Tooltip>{isAdmin && <><Tooltip title="Edit Warehouse"><IconButton color="warning" onClick={() => onEdit(warehouse)}><Edit size={18} /></IconButton></Tooltip><Tooltip title="Delete Warehouse"><IconButton color="error" onClick={() => onDelete(warehouse)}><Trash2 size={18} /></IconButton></Tooltip></>}</Stack>;
  const heading = (field, label) => <TableCell sx={{ fontWeight: 600, bgcolor: 'grey.50' }}><TableSortLabel active={sortBy === field} direction={sortBy === field ? sortOrder : 'asc'} onClick={() => onSort(field)}>{label}</TableSortLabel></TableCell>;
  return <Paper variant="outlined" sx={{ overflow: 'hidden' }}>
    <Stack divider={<Box borderTop={1} borderColor="divider" />} sx={{ display: { xs: 'flex', md: 'none' } }}>{items.map((warehouse) => <Card key={warehouse.id} square elevation={0} sx={{ p: 2 }}><Stack spacing={1.5}><Stack direction="row" alignItems="center" spacing={1.5}><Avatar variant="rounded"><Warehouse size={22} /></Avatar><Box minWidth={0}><Typography fontWeight={600} noWrap>{warehouse.name}</Typography><Chip size="small" label={warehouse.code} color="primary" variant="outlined" /></Box></Stack><Detail label="Location" value={warehouse.location || 'Not specified'} secondary={warehouse.address} />{(warehouse.phone || warehouse.email) && <Detail label="Contact" value={warehouse.phone} secondary={warehouse.email} />}<Detail label="Updated" value={date(warehouse.updatedAt || warehouse.createdAt)} /><Box pt={1} borderTop={1} borderColor="divider">{actions(warehouse)}</Box></Stack></Card>)}</Stack>
    <TableContainer sx={{ display: { xs: 'none', md: 'block' } }}><Table sx={{ minWidth: 980 }}><TableHead><TableRow>{heading('name','Warehouse')}{heading('code','Code')}{heading('location','Location')}<TableCell sx={{ fontWeight: 600, bgcolor: 'grey.50' }}>Contact</TableCell>{heading('updatedAt','Last Updated')}<TableCell align="right" sx={{ fontWeight: 600, bgcolor: 'grey.50' }}>Actions</TableCell></TableRow></TableHead><TableBody>{items.map((warehouse) => <TableRow key={warehouse.id} hover><TableCell><Stack direction="row" alignItems="center" spacing={1.5}><Warehouse size={26} /><Typography fontWeight={500}>{warehouse.name}</Typography></Stack></TableCell><TableCell><Chip size="small" label={warehouse.code} color="primary" variant="outlined" /></TableCell><TableCell><Typography variant="body2">{warehouse.location || 'Not specified'}</Typography><Typography variant="caption" color="text.secondary">{warehouse.address}</Typography></TableCell><TableCell>{warehouse.phone && <Stack direction="row" spacing={0.75}><Phone size={14} /><Typography variant="body2">{warehouse.phone}</Typography></Stack>}{warehouse.email && <Stack direction="row" spacing={0.75} mt={0.5}><Mail size={14} /><Typography variant="caption" color="text.secondary">{warehouse.email}</Typography></Stack>}</TableCell><TableCell>{date(warehouse.updatedAt || warehouse.createdAt)}</TableCell><TableCell>{actions(warehouse)}</TableCell></TableRow>)}</TableBody></Table></TableContainer>
    {items.length === 0 && <Box py={5} textAlign="center"><Warehouse size={48} color="#bdbdbd" /><Typography variant="h6" mt={1}>No warehouses found</Typography><Typography variant="body2" color="text.secondary">Try adjusting your search criteria</Typography></Box>}
  </Paper>;
}
const Detail = ({ label, value, secondary }) => <Box><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="body2">{value || '—'}</Typography>{secondary && <Typography variant="caption" color="text.secondary">{secondary}</Typography>}</Box>;
